#
# This is free software, lisence use MIT.
#
# Openwrt 19.07 enabled with Lienol's Passwall
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 Lienol/openwrt-package
# Modified by kiss2u
# <https://github.com/kiss2u>
#

name: OpenWrt-CL
on:
  # push:
  #   tags:
  #     - 'V*'
   push:
     branches:
       - master
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Environment
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler	  
     
	 - name: Update feeds
	run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

     # - name: Costom configure file
     #   run: |
     #    rm -f ./.config*
     #     touch ./.config
     #     sed -i 's/^[ \t]*//g' ./.config
     #     make defconfig
	 
     # - name: Load custom configuration
     #  env:
     #    CONFIG_FILE: '.config'
     #    DIY_SH: 'diy.sh'
     #  run: |
     #    [ -e files ] && mv files openwrt/files
     #    [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
     #    chmod +x $DIY_SH
     #    cd openwrt
     #    ../$DIY_SH
     #    make defconfig
	 
	 - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."

    make -j$(nproc) V=s
      - name: Assemble artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./artifact/
